const phrases = [
    "hello",
    "goodbye",
    "please",
    "thank you",
    "sorry",
    "yes",
    "no",
    "help",
    "excuse me",
    "nice to meet you",
    "how are you?",
    "fine",
    "name",
    "age",
    "where",
    "when",
    "why",
    "how",
    "who",
    "family",
    "mother",
    "father",
    "brother",
    "sister",
    "friend",
    "home",
    "food",
    "drink",
    "hungry",
    "thirsty",
    "toilet",
    "sleep",
    "happy",
    "sad",
    "angry",
    "love",
    "like",
    "dislike",
    "learn",
    "sign",
    "hospital",
    "book",
    "pen",
    "paper",
    "computer",
    "phone",
    "music",
    "movie",
    "dance",
    "sport",
    "travel",
    "beach",
    "mountain",
    "city",
    "country",
    "car",
    "bicycle",
    "bus",
    "train",
    "airplane",
    "money",
    "time",
    "weather",
    "work",
    "study",
    "breakfast",
    "lunch",
    "dinner",
    "snack",
    "vegetable",
    "fruit",
    "meat",
    "fish",
    "cheese",
    "bread",
    "rice",
    "noodle",
    "soup",
    "salad",
    "juice",
    "coffee",
    "tea",
    "water",
    "milk",
    "beer",
    "wine",
    "cocktail",
    "birthday",
    "holiday",
    "wedding",
    "party",
    "gift",
    "shopping",
    "clothes",
    "shoes",
    "hat",
    "bag",
    "jewelry",
    "watch",
    "glasses",
    "makeup",
    "hair",
    "toothbrush",
    "shampoo",
    "soap",
    "towel",
    "bed",
    "pillow",
    "blanket",
    "chair",
    "table",
    "lamp",
    "window",
    "door",
    "wall",
    "floor",
    "ceiling",
    "mirror",
    "picture",
    "plant",
    "cat",
    "dog",
    "bird",
    "fish",
    "insect",
    "zoo",
    "garden",
    "beauty",
    "clean",
    "dirty",
    "big",
    "small",
    "fast",
    "slow",
    "hot",
    "cold",
    "heavy",
    "light",
    "hard",
    "soft",
    "loud",
    "quiet",
    "new",
    "old",
    "young",
    "old",
    "beautiful",
    "ugly",
    "expensive",
    "cheap",
    "happy",
    "sad",
    "exciting",
    "boring",
    "fun",
    "boring",
    "difficult",
    "easy",
    "interesting",
    "boring",
    "important",
    "unimportant",
    "healthy",
    "unhealthy",
    "busy",
    "free",
    "tired",
    "energetic",
    "calm",
    "angry",
    "patient",
    "impatient",
    "generous",
    "stingy",
    "polite",
    "impolite",
    "brave",
    "cowardly",
    "honest",
    "dishonest",
    "kind",
    "unkind",
    "friendly",
    "unfriendly",
    "confused",
    "clear",
    "safe",
    "dangerous",
    "open",
    "closed",
    "freezing",
    "boiling",
    "crowded",
    "empty",
    "wet",
    "dry",
    "cloudy",
    "sunny",
    "windy",
    "rainy",
    "snowy",
    "thunderstorm",
    "earthquake",
    "fire",
    "flood",
    "hurricane",
    "tornado",
    "volcano",
    "forest",
    "ocean",
    "river",
    "mountain",
    "valley",
    "desert",
    "beauty",
    "ugliness",
    "love",
    "hate",
    "hope",
    "fear",
    "courage",
    "cowardice",
    "happiness",
    "sadness",
    "excitement",
    "boredom",
    "pleasure",
    "pain",
    "success",
    "failure",
    "friendship",
    "loneliness",
    "peace",
    "war",
    "freedom",
    "slavery",
    "equality",
    "inequality",
    "justice",
    "injustice",
    "kindness",
    "cruelty",
    "wisdom",
    "ignorance",
    "truth",
    "lies",
    "faith",
    "doubt",
    "believe",
    "disbelieve",
    "hopeful",
    "hopeless",
    "optimistic",
    "pessimistic",
    "caring",
    "uncaring",
    "respectful",
    "disrespectful",
    "thankful",
    "unthankful",
    "helpful",
    "unhelpful",
    "positive",
    "negative",
    "patient",
    "impatient",
    "generous",
    "stingy",
    "polite",
    "impolite",
    "brave",
    "cowardly",
    "honest",
    "dishonest",
    "kind",
    "unkind",
    "friendly",
    "unfriendly",
    "confused",
    "clear",
    "safe",
    "dangerous",
    "open",
    "closed",
    "freezing",
    "boiling",
    "crowded",
    "empty",
    "wet",
    "dry",
    "cloudy",
    "sunny",
    "windy",
    "rainy",
    "snowy",
    "thunderstorm",
    "earthquake",
    "fire",
    "flood",
    "hurricane",
    "tornado",
    "volcano",
    "forest",
    "ocean",
    "river",
    "mountain",
    "valley",
    "desert"
  ];

const imageContainer = document.getElementById('image-container');
const startButton = document.getElementById('start-button');
const inputText = document.getElementById('input-text');
const submitButton = document.getElementById('submit-button');
const message = document.getElementById('message');
const scoreElement = document.getElementById('score');
let currentPhrase = '';
let score = 0;

startButton.addEventListener('click', () => {
    startNewRound();
});

submitButton.addEventListener('click', () => {
    if (inputText.value.toLowerCase() === currentPhrase) {
        score++;
        message.textContent = 'Correct! Well done!';
        message.style.color = 'green';
        scoreElement.textContent = score;
        setTimeout(() => {
            startNewRound();
        }, 1500);
    } else {
        alert(`Game over! The correct word was "${currentPhrase}".`);
        resetGame();
    }
});

function startNewRound() {
    startButton.disabled = true;
    inputText.disabled = false;
    submitButton.disabled = true; // Disable the submit button initially
    message.textContent = '';
    inputText.value = '';
    inputText.focus();
    currentPhrase = phrases[Math.floor(Math.random() * phrases.length)];
    displayPhrase();
}

function displayPhrase() {
    imageContainer.innerHTML = '';
    let imagesDisplayed = 0;

    for (let i = 0; i < currentPhrase.length; i++) {
        const letter = currentPhrase[i].toUpperCase();
        const img = document.createElement('img');
        img.src = `../View/assets/${letter}.png`;
        img.className = 'img-letter';
        setTimeout(() => {
            imageContainer.appendChild(img);
            imagesDisplayed++;

            if (imagesDisplayed === currentPhrase.length) {
                submitButton.disabled = false; // Enable the submit button after all images are shown
            }
        }, 400 * i);
    }
}

function resetGame() {
    startButton.disabled = false;
    inputText.disabled = true;
    submitButton.disabled = true;
    message.textContent = '';
    inputText.value = '';
    score = 0;
    scoreElement.textContent = score;
    imageContainer.innerHTML = '';
}
